// Code generated by goctl. DO NOT EDIT.
package types

type GroupResp struct {
	Gid            string `json:"gid"`            // 分组标识
	Name           string `json:"name"`           // 分组名称
	SortOrder      int    `json:"sortOrder"`      // 排序序号
	ShortLinkCount int64  `json:"shortLinkCount"` // 短链接数量
	CreateTime     string `json:"createTime"`     // 创建时间
	UpdateTime     string `json:"updateTime"`     // 更新时间
}

type RecycleBinItem struct {
	Gid          string `json:"gid"`          // 分组标识
	FullShortUrl string `json:"fullShortUrl"` // 完整短链接
	CreateTime   string `json:"createTime"`   // 创建时间
}

type RecycleBinPageReq struct {
	Current int64 `form:"current,default=1" validate:"required,min=1"`       // 当前页码
	Size    int64 `form:"size,default=10" validate:"required,min=1,max=100"` // 每页大小
}

type RecycleBinRecoverReq struct {
	Gid          string `json:"gid" validate:"required"`          // 分组标识
	FullShortUrl string `json:"fullShortUrl" validate:"required"` // 完整短链接
}

type RecycleBinRemoveReq struct {
	Gid          string `json:"gid" validate:"required"`          // 分组标识
	FullShortUrl string `json:"fullShortUrl" validate:"required"` // 完整短链接
}

type RecycleBinResp struct {
	List  []RecycleBinItem `json:"list"`  // 列表数据
	Total int64            `json:"total"` // 总数
}

type RecycleBinSaveReq struct {
	Gid          string `json:"gid" validate:"required"`          // 分组标识
	FullShortUrl string `json:"fullShortUrl" validate:"required"` // 完整短链接
}

type ShortLinkGroupSaveReq struct {
	Name string `json:"name" validate:"required,max=32"` // 分组名称
}

type ShortLinkGroupSortReq struct {
	Gid       string `json:"gid" validate:"required"` // 分组标识
	SortOrder int    `json:"sortOrder"`               // 排序序号
}

type ShortLinkGroupUpdateReq struct {
	Gid  string `json:"gid" validate:"required"`         // 分组标识
	Name string `json:"name" validate:"required,max=32"` // 分组名称
}

type UserLoginReq struct {
	Username string `json:"username" validate:"required"` // 用户名
	Password string `json:"password" validate:"required"` // 密码
}

type UserLoginResp struct {
	Token string `json:"token"` // JWT Token
}

type UserRegisterReq struct {
	Username string `json:"username" validate:"required,min=4,max=32"` // 用户名
	Password string `json:"password" validate:"required,min=6,max=32"` // 密码
	RealName string `json:"realName" validate:"required"`              // 真实姓名
	Phone    string `json:"phone" validate:"required,phone"`           // 手机号
	Mail     string `json:"mail" validate:"required,email"`            // 邮箱
}

type UserRegisterResp struct {
	Username   string `json:"username"`   // 用户名
	CreateTime string `json:"createTime"` // 创建时间
	Message    string `json:"message"`    // 响应消息
}

type UserResp struct {
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realName"`   // 真实姓名
	Phone      string `json:"phone"`      // 手机号
	Mail       string `json:"mail"`       // 邮箱
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
}

type UserUpdateReq struct {
	Username string `json:"username" validate:"required"`              // 用户名
	Password string `json:"password,optional"`                         // 密码
	RealName string `json:"realName,optional"`                         // 真实姓名
	Phone    string `json:"phone,optional" validate:"omitempty,phone"` // 手机号
	Mail     string `json:"mail,optional" validate:"omitempty,email"`  // 邮箱
}
