// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	group "shorterurl/user/api/internal/handler/group"
	recycle "shorterurl/user/api/internal/handler/recycle"
	user "shorterurl/user/api/internal/handler/user"
	"shorterurl/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/short-link/admin/v1/group",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/short-link/admin/v1/group",
				Handler: group.ListGroupsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/short-link/admin/v1/group",
				Handler: group.UpdateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/short-link/admin/v1/group",
				Handler: group.DeleteGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/short-link/admin/v1/group/sort",
				Handler: group.SortGroupsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 分页查询回收站短链接
				Method:  http.MethodGet,
				Path:    "/recycle-bin/page",
				Handler: recycle.RecycleBinPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/short-link/admin/v1/actual/user/:username",
				Handler: user.ApiActualUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/short-link/admin/v1/user",
				Handler: user.ApiUserRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/short-link/admin/v1/user",
				Handler: user.ApiUserUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/short-link/admin/v1/user/:username",
				Handler: user.ApiUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/short-link/admin/v1/user/check-login",
				Handler: user.ApiCheckLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/short-link/admin/v1/user/has-username",
				Handler: user.ApiCheckUsernameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/short-link/admin/v1/user/login",
				Handler: user.ApiUserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/short-link/admin/v1/user/logout",
				Handler: user.ApiLogoutHandler(serverCtx),
			},
		},
	)
}
