// Code generated by goctl. DO NOT EDIT.
package types

type UserCheckLoginReq struct {
	Username string `json:"username" validate:"required"` // 用户名
	Token    string `json:"token" validate:"required"`    // Token
}

type UserCheckUsernameReq struct {
	Username string `form:"username" validate:"required"` // 用户名
}

type UserCheckUsernameResp struct {
	Exist bool `json:"exist"` // 是否存在
}

type UserInfoResp struct {
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realName"`   // 真实姓名
	Phone      string `json:"phone"`      // 手机号
	Mail       string `json:"mail"`       // 邮箱
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
}

type UserLoginReq struct {
	Username string `json:"username" validate:"required"` // 用户名
	Password string `json:"password" validate:"required"` // 密码
}

type UserLoginResp struct {
	Token      string `json:"token"`      //  Token
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realName"`   // 真实姓名
	CreateTime string `json:"createTime"` // 创建时间
}

type UserRegisterReq struct {
	Username string `json:"username" validate:"required,min=4,max=32"` // 用户名
	Password string `json:"password" validate:"required,min=6,max=32"` // 密码
	RealName string `json:"realName" validate:"required"`              // 真实姓名
	Phone    string `json:"phone" validate:"required,phone"`           // 手机号
	Mail     string `json:"mail" validate:"required,email"`            // 邮箱
}

type UserRegisterResp struct {
	Username   string `json:"username"`   // 用户名
	CreateTime string `json:"createTime"` // 创建时间
	Message    string `json:"message"`    // 响应消息
}

type UserUpdatePasswordReq struct {
	Username    string `json:"username" validate:"required"`                 // 用户名
	OldPassword string `json:"oldPassword" validate:"required"`              // 旧密码
	NewPassword string `json:"newPassword" validate:"required,min=6,max=32"` // 新密码
}

type UserUpdateReq struct {
	Username string `json:"username" validate:"required"`              // 用户名
	Password string `json:"password,optional"`                         // 密码（可选）
	RealName string `json:"realName,optional"`                         // 真实姓名（可选）
	Phone    string `json:"phone,optional" validate:"omitempty,phone"` // 手机号（可选）
	Mail     string `json:"mail,optional" validate:"omitempty,email"`  // 邮箱（可选）
}

type UserUpdateResp struct {
	Code string `json:"code"` // 响应码
}

type UserUsernameReq struct {
	Username string `path:"username"` // 用户名
}
