// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AccessRecord struct {
	Ip         string `json:"ip"`         // IP地址
	Browser    string `json:"browser"`    // 浏览器
	Os         string `json:"os"`         // 操作系统
	Network    string `json:"network"`    // 网络环境
	Device     string `json:"device"`     // 设备
	Locale     string `json:"locale"`     // 地域
	AccessTime string `json:"accessTime"` // 访问时间
}

type AccessRecordPageResp struct {
	Records []AccessRecord `json:"records"` // 访问记录列表
	Total   int64          `json:"total"`   // 总记录数
	Size    int64          `json:"size"`    // 每页大小
	Current int64          `json:"current"` // 当前页码
}

type BatchCreateLinkReq struct {
	OriginUrls    []string `json:"originUrls" validate:"required,min=1"` // 原始URL列表
	Describes     []string `json:"describes" validate:"required,min=1"`  // 描述列表
	Gid           string   `json:"gid" validate:"required"`              // 分组标识
	CreatedType   int      `json:"createdType,default=0"`                // 创建类型
	ValidDateType int      `json:"validDateType"`                        // 有效期类型
	ValidDate     string   `json:"validDate,optional"`                   // 有效日期
}

type BatchCreateLinkResp struct {
	Total         int            `json:"total"`         // 总数
	BaseLinkInfos []LinkBaseInfo `json:"baseLinkInfos"` // 基本链接信息列表
}

type BrowserStat struct {
	Browser string  `json:"browser"` // 浏览器
	Cnt     int64   `json:"cnt"`     // 数量
	Ratio   float64 `json:"ratio"`   // 比例
}

type CreateLinkReq struct {
	OriginUrl     string `json:"originUrl" validate:"required"` // 原始URL
	Gid           string `json:"gid" validate:"required"`       // 分组标识
	CreatedType   int    `json:"createdType,default=0"`         // 创建类型 0:接口创建 1:控制台创建
	ValidDateType int    `json:"validDateType"`                 // 有效期类型 0:永久有效 1:自定义
	ValidDate     string `json:"validDate,optional"`            // 有效日期
	Describe      string `json:"describe,optional"`             // 描述
}

type CreateLinkResp struct {
	FullShortUrl string `json:"fullShortUrl"` // 完整短链接
	OriginUrl    string `json:"originUrl"`    // 原始URL
	Gid          string `json:"gid"`          // 分组标识
}

type DeviceStat struct {
	Device string  `json:"device"` // 设备
	Cnt    int64   `json:"cnt"`    // 数量
	Ratio  float64 `json:"ratio"`  // 比例
}

type GetUrlTitleReq struct {
	Url string `form:"url" validate:"required,url"` // 目标网站地址
}

type LinkBaseInfo struct {
	FullShortUrl string `json:"fullShortUrl"` // 完整短链接
	OriginUrl    string `json:"originUrl"`    // 原始URL
	Describe     string `json:"describe"`     // 描述
}

type LocaleCnStat struct {
	Locale string  `json:"locale"` // 地区
	Cnt    int64   `json:"cnt"`    // 数量
	Ratio  float64 `json:"ratio"`  // 比例
}

type NetworkStat struct {
	Network string  `json:"network"` // 网络类型
	Cnt     int64   `json:"cnt"`     // 数量
	Ratio   float64 `json:"ratio"`   // 比例
}

type OsStat struct {
	Os    string  `json:"os"`    // 操作系统
	Cnt   int64   `json:"cnt"`   // 数量
	Ratio float64 `json:"ratio"` // 比例
}

type PageLinkReq struct {
	Current int    `form:"current,default=1"`       // 页码
	Size    int    `form:"size,default=10"`         // 每页大小
	Gid     string `form:"gid" validate:"required"` // 分组标识
}

type PageLinkResp struct {
	Records []ShortLinkRecord `json:"records"` // 记录列表
	Total   int64             `json:"total"`   // 总记录数
	Size    int               `json:"size"`    // 每页大小
	Current int               `json:"current"` // 当前页
}

type PvUvUipStats struct {
	Date string `json:"date"` // 日期
	Pv   int64  `json:"pv"`   // 访问量
	Uv   int64  `json:"uv"`   // 独立访客数
	Uip  int64  `json:"uip"`  // IP数
}

type RecycleBinOperateReq struct {
	Gid          string `json:"gid" validate:"required"`          // 分组标识
	FullShortUrl string `json:"fullShortUrl" validate:"required"` // 完整短链接
}

type RecycleBinPageReq struct {
	Gid     string `form:"gid" validate:"required"` // 分组标识，必选项
	Current int    `form:"current,default=1"`       // 当前页码，从1开始
	Size    int    `form:"size,default=10"`         // 每页记录数
}

type RecycleBinPageResp struct {
	Records []ShortLinkPageRecordDTO `json:"records"` // 短链接记录列表
	Total   int64                    `json:"total"`   // 总记录数
	Size    int                      `json:"size"`    // 每页大小
	Current int                      `json:"current"` // 当前页码
}

type ShortLinkAccessRecordReq struct {
	FullShortUrl string `form:"fullShortUrl" validate:"required"` // 完整短链接
	Gid          string `form:"gid" validate:"required"`          // 分组标识
	StartDate    string `form:"startDate" validate:"required"`    // 开始日期
	EndDate      string `form:"endDate" validate:"required"`      // 结束日期
	EnableStatus int    `form:"enableStatus,optional"`            // 启用状态
	Current      int64  `form:"current,default=1"`                // 当前页码
	Size         int64  `form:"size,default=10"`                  // 每页大小
}

type ShortLinkGroupAccessRecordReq struct {
	Gid       string `form:"gid" validate:"required"`       // 分组标识
	StartDate string `form:"startDate" validate:"required"` // 开始日期
	EndDate   string `form:"endDate" validate:"required"`   // 结束日期
	Current   int64  `form:"current,default=1"`             // 当前页码
	Size      int64  `form:"size,default=10"`               // 每页大小
}

type ShortLinkGroupDeleteReq struct {
	Gid string `form:"gid" validate:"required"` // 分组标识
}

type ShortLinkGroupResp struct {
	Gid            string `json:"gid"`            // 分组标识
	Name           string `json:"name"`           // 分组名称
	SortOrder      int    `json:"sortOrder"`      // 排序序号
	ShortLinkCount int    `json:"shortLinkCount"` // 短链接数量
}

type ShortLinkGroupSaveReq struct {
	Name string `json:"name" validate:"required"` // 分组名称
}

type ShortLinkGroupSortReq struct {
	Groups []SortGroup `json:"groups" validate:"required,dive,required"`
}

type ShortLinkGroupStatsReq struct {
	Gid       string `form:"gid" validate:"required"`       // 分组标识
	StartDate string `form:"startDate" validate:"required"` // 开始日期
	EndDate   string `form:"endDate" validate:"required"`   // 结束日期
}

type ShortLinkGroupUpdateReq struct {
	Gid  string `json:"gid" validate:"required"`  // 分组标识
	Name string `json:"name" validate:"required"` // 分组名称
}

type ShortLinkPageRecordDTO struct {
	Id            int64  `json:"id"`            // 短链ID
	Domain        string `json:"domain"`        // 域名
	ShortUri      string `json:"shortUri"`      // 短链接URI
	FullShortUrl  string `json:"fullShortUrl"`  // 完整短链接
	OriginUrl     string `json:"originUrl"`     // 原始链接
	Gid           string `json:"gid"`           // 分组标识
	ValidDateType int    `json:"validDateType"` // 有效期类型：0永久有效，1自定义
	ValidDate     string `json:"validDate"`     // 有效期
	CreateTime    string `json:"createTime"`    // 创建时间
	Describe      string `json:"describe"`      // 描述
	Favicon       string `json:"favicon"`       // 网站图标
	EnableStatus  int    `json:"enableStatus"`  // 启用状态：0启用，1未启用
	TotalPv       int64  `json:"totalPv"`       // 总访问量
	TodayPv       int64  `json:"todayPv"`       // 今日访问量
	TotalUv       int64  `json:"totalUv"`       // 总独立访客数
	TodayUv       int64  `json:"todayUv"`       // 今日独立访客数
	TotalUip      int64  `json:"totalUip"`      // 总IP数
	TodayUip      int64  `json:"todayUip"`      // 今日IP数
}

type ShortLinkRecord struct {
	Id            int64  `json:"id"`            // 短链ID
	Domain        string `json:"domain"`        // 域名
	ShortUri      string `json:"shortUri"`      // 短链接URI
	FullShortUrl  string `json:"fullShortUrl"`  // 完整短链接
	OriginUrl     string `json:"originUrl"`     // 原始链接
	Gid           string `json:"gid"`           // 分组标识
	ValidDateType int    `json:"validDateType"` // 有效期类型：0永久有效，1自定义
	ValidDate     string `json:"validDate"`     // 有效期
	CreateTime    string `json:"createTime"`    // 创建时间
	Describe      string `json:"describe"`      // 描述
	Favicon       string `json:"favicon"`       // 网站图标
	EnableStatus  int    `json:"enableStatus"`  // 启用状态：0启用，1未启用
	TotalPv       int64  `json:"totalPv"`       // 总访问量
	TodayPv       int64  `json:"todayPv"`       // 今日访问量
	TotalUv       int64  `json:"totalUv"`       // 总独立访客数
	TodayUv       int64  `json:"todayUv"`       // 今日独立访客数
	TotalUip      int64  `json:"totalUip"`      // 总IP数
	TodayUip      int64  `json:"todayUip"`      // 今日IP数
}

type ShortLinkRedirectReq struct {
	ShortUri string `path:"short_uri"` // 短链接URI
}

type ShortLinkStatsReq struct {
	FullShortUrl string `form:"fullShortUrl" validate:"required"` // 完整短链接
	Gid          string `form:"gid" validate:"required"`          // 分组标识
	EnableStatus int    `form:"enableStatus,optional"`            // 启用状态
	StartDate    string `form:"startDate" validate:"required"`    // 开始日期
	EndDate      string `form:"endDate" validate:"required"`      // 结束日期
}

type ShortLinkStatsRespDTO struct {
	PvUvUipStatsList    []PvUvUipStats `json:"pvUvUipStatsList"`    // PV/UV/UIP统计列表
	OverallPvUvUipStats PvUvUipStats   `json:"overallPvUvUipStats"` // 总体PV/UV/UIP统计
	LocaleCnStats       []LocaleCnStat `json:"localeCnStats"`       // 地域统计
	HourStats           []int          `json:"hourStats"`           // 小时访问详情
	TopIpStats          []TopIpStat    `json:"topIpStats"`          // 高频访问IP详情
	WeekdayStats        []int          `json:"weekdayStats"`        // 一周访问详情
	BrowserStats        []BrowserStat  `json:"browserStats"`        // 浏览器统计
	OsStats             []OsStat       `json:"osStats"`             // 操作系统统计
	UvTypeStats         []UvTypeStat   `json:"uvTypeStats"`         // 访客类型统计
	DeviceStats         []DeviceStat   `json:"deviceStats"`         // 设备统计
	NetworkStats        []NetworkStat  `json:"networkStats"`        // 网络统计
}

type SortGroup struct {
	Gid       string `json:"gid" validate:"required"`       // 分组标识
	SortOrder int    `json:"sortOrder" validate:"required"` // 排序序号
}

type SuccessResp struct {
	Code    string `json:"code"`    // 响应码
	Success bool   `json:"success"` // 是否成功
}

type TopIpStat struct {
	Ip    string  `json:"ip"`    // IP地址
	Cnt   int64   `json:"cnt"`   // 访问次数
	Ratio float64 `json:"ratio"` // 比例
}

type UpdateLinkReq struct {
	FullShortUrl  string `json:"fullShortUrl" validate:"required"` // 完整短链接
	OriginGid     string `json:"originGid" validate:"required"`    // 原始分组标识
	Gid           string `json:"gid" validate:"required"`          // 新分组标识
	OriginUrl     string `json:"originUrl" validate:"required"`    // 原始URL
	Describe      string `json:"describe,optional"`                // 描述
	ValidDateType int    `json:"validDateType"`                    // 有效期类型
	ValidDate     string `json:"validDate,optional"`               // 有效日期
}

type UrlTitleResp struct {
	Data string `json:"data"` // 网站标题
}

type UserCheckLoginReq struct {
	Username string `form:"username" validate:"required"` // 用户名
	Token    string `form:"token" validate:"required"`    // Token
}

type UserCheckUsernameReq struct {
	Username string `form:"username" validate:"required"` // 用户名
}

type UserCheckUsernameResp struct {
	Data    bool   `json:"data"`    // 是否存在
	Success bool   `json:"success"` // 是否成功
	Code    string `json:"code"`    // 响应码
}

type UserInfoResp struct {
	Id         int64  `json:"id"`         // 用户ID
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realname"`   // 真实姓名
	Phone      string `json:"phone"`      // 手机号
	Mail       string `json:"mail"`       // 邮箱
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
}

type UserLogOutReq struct {
	Username string `form:"username" validate:"required"` // 用户名
	Token    string `form:"token" validate:"required"`    // Token
}

type UserLoginReq struct {
	Username string `json:"username" validate:"required"` // 用户名，只能使用ASCII字符
	Password string `json:"password" validate:"required"` // 密码
}

type UserLoginResp struct {
	Token      string `json:"token"`      //  Token
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realname"`   // 真实姓名
	CreateTime string `json:"createTime"` // 创建时间
}

type UserRegisterReq struct {
	Username string `json:"username" validate:"required,min=4,max=32"` // 用户名，只能使用ASCII字符
	Password string `json:"password" validate:"required,min=6,max=32"` // 密码
	RealName string `json:"realname" validate:"required"`              // 真实姓名
	Phone    string `json:"phone" validate:"required,phone"`           // 手机号
	Mail     string `json:"mail" validate:"required,email"`            // 邮箱
}

type UserRegisterResp struct {
	Username   string `json:"username"`   // 用户名
	CreateTime string `json:"createTime"` // 创建时间
	Message    string `json:"message"`    // 响应消息
}

type UserUpdateReq struct {
	Username string `json:"username" validate:"required"`              // 用户名
	Password string `json:"password,optional"`                         // 密码（可选）
	RealName string `json:"realName,optional"`                         // 真实姓名（可选）
	Phone    string `json:"phone,optional" validate:"omitempty,phone"` // 手机号（可选）
	Mail     string `json:"mail,optional" validate:"omitempty,email"`  // 邮箱（可选）
}

type UserUpdateResp struct {
	Code string `json:"code"` // 响应码
}

type UserUsernameReq struct {
	Username string `path:"username"` // 用户名
}

type UvTypeStat struct {
	UvType string  `json:"uvType"` // 访客类型
	Cnt    int64   `json:"cnt"`    // 数量
	Ratio  float64 `json:"ratio"`  // 比例
}
