// Code generated by goctl. DO NOT EDIT.
package types

type RecycleBinPageReq struct {
	GidList []string `json:"gidList,optional"`  // 分组标识列表，可选
	Current int      `form:"current,default=1"` // 当前页码，从1开始
	Size    int      `form:"size,default=10"`   // 每页记录数
}

type RecycleBinPageResp struct {
	Records []ShortLinkPageRecordDTO `json:"records"` // 短链接记录列表
	Total   int64                    `json:"total"`   // 总记录数
	Size    int                      `json:"size"`    // 每页大小
	Current int                      `json:"current"` // 当前页码
}

type ShortLinkGroupDeleteReq struct {
	Gid string `form:"gid" validate:"required"` // 分组标识
}

type ShortLinkGroupResp struct {
	Gid            string `json:"gid"`            // 分组标识
	Name           string `json:"name"`           // 分组名称
	SortOrder      int    `json:"sortOrder"`      // 排序序号
	ShortLinkCount int    `json:"shortLinkCount"` // 短链接数量
}

type ShortLinkGroupSaveReq struct {
	Name string `json:"name" validate:"required"` // 分组名称
}

type ShortLinkGroupSortReq struct {
	Groups []SortGroup `json:"groups" validate:"required,dive,required"`
}

type ShortLinkGroupUpdateReq struct {
	Gid  string `json:"gid" validate:"required"`  // 分组标识
	Name string `json:"name" validate:"required"` // 分组名称
}

type ShortLinkPageRecordDTO struct {
	Id            int64  `json:"id"`            // 短链��ID
	Domain        string `json:"domain"`        // 域名
	ShortUri      string `json:"shortUri"`      // 短链接URI
	FullShortUrl  string `json:"fullShortUrl"`  // 完整短链接
	OriginUrl     string `json:"originUrl"`     // 原始链接
	Gid           string `json:"gid"`           // 分组标识
	ValidDateType int    `json:"validDateType"` // 有效期类型：0永久有效，1自定义
	ValidDate     string `json:"validDate"`     // 有效期
	CreateTime    string `json:"createTime"`    // 创建时间
	Describe      string `json:"describe"`      // 描述
	Favicon       string `json:"favicon"`       // 网站图标
	EnableStatus  int    `json:"enableStatus"`  // 启用状态：0启用，1未启用
	TotalPv       int64  `json:"totalPv"`       // 总访问量
	TodayPv       int64  `json:"todayPv"`       // 今日访问量
	TotalUv       int64  `json:"totalUv"`       // 总独立访客数
	TodayUv       int64  `json:"todayUv"`       // 今日独立访客数
	TotalUip      int64  `json:"totalUip"`      // 总IP数
	TodayUip      int64  `json:"todayUip"`      // 今日IP数
}

type SortGroup struct {
	Gid       string `json:"gid" validate:"required"`       // 分组标识
	SortOrder int    `json:"sortOrder" validate:"required"` // 排序序号
}

type SuccessResp struct {
	Code    string `json:"code"`    // 响应码
	Success bool   `json:"success"` // 是否成功
}

type UserCheckLoginReq struct {
	Username string `form:"username" validate:"required"` // 用户名
	Token    string `form:"token" validate:"required"`    // Token
}

type UserCheckUsernameReq struct {
	Username string `form:"username" validate:"required"` // 用户名
}

type UserCheckUsernameResp struct {
	Data    bool   `json:"data"`    // 是否存在
	Success bool   `json:"success"` // 是否成功
	Code    string `json:"code"`    // 响应码
}

type UserInfoResp struct {
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realname"`   // 真实姓名
	Phone      string `json:"phone"`      // 手机号
	Mail       string `json:"mail"`       // 邮箱
	CreateTime string `json:"createTime"` // 创建时间
	UpdateTime string `json:"updateTime"` // 更新时间
}

type UserLogOutReq struct {
	Username string `form:"username" validate:"required"` // 用户名
	Token    string `form:"token" validate:"required"`    // Token
}

type UserLoginReq struct {
	Username string `json:"username" validate:"required"` // 用户名
	Password string `json:"password" validate:"required"` // 密码
}

type UserLoginResp struct {
	Token      string `json:"token"`      //  Token
	Username   string `json:"username"`   // 用户名
	RealName   string `json:"realname"`   // 真实姓名
	CreateTime string `json:"createTime"` // 创建时间
}

type UserRegisterReq struct {
	Username string `json:"username" validate:"required,min=4,max=32"` // 用户名
	Password string `json:"password" validate:"required,min=6,max=32"` // 密码
	RealName string `json:"realname" validate:"required"`              // 真实姓名
	Phone    string `json:"phone" validate:"required,phone"`           // 手机号
	Mail     string `json:"mail" validate:"required,email"`            // 邮箱
}

type UserRegisterResp struct {
	Username   string `json:"username"`   // 用户名
	CreateTime string `json:"createTime"` // 创建时间
	Message    string `json:"message"`    // 响应消息
}

type UserUpdateReq struct {
	Username string `json:"username" validate:"required"`              // 用户名
	Password string `json:"password,optional"`                         // 密码（可选）
	RealName string `json:"realName,optional"`                         // 真实姓名（可选）
	Phone    string `json:"phone,optional" validate:"omitempty,phone"` // 手机号（可选）
	Mail     string `json:"mail,optional" validate:"omitempty,email"`  // 邮箱（可选）
}

type UserUpdateResp struct {
	Code string `json:"code"` // 响应码
}

type UserUsernameReq struct {
	Username string `path:"username"` // 用户名
}
