// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user/rpc/user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                 // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                 // 密码
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"` // 真实姓名
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                       // 手机号
	Mail          string                 `protobuf:"bytes,5,opt,name=mail,proto3" json:"mail,omitempty"`                         // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

// 用户注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                       // 用户名
	CreateTime    string                 `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                         // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 用户登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                             // Token
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                       // 用户名
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`       // 真实姓名
	CreateTime    string                 `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *LoginResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

// 用户信息响应
type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 用户ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                       // 用户名
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`       // 真实姓名
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                             // 手机号
	Mail          string                 `protobuf:"bytes,5,opt,name=mail,proto3" json:"mail,omitempty"`                               // 邮箱
	CreateTime    string                 `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间
	UpdateTime    string                 `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoResponse) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UserInfoResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfoResponse) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserInfoResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserInfoResponse) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 用户更新请求
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                 // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                 // 密码（可选）
	RealName      string                 `protobuf:"bytes,3,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"` // 真实姓名（可选）
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                       // 手机号（可选）
	Mail          string                 `protobuf:"bytes,5,opt,name=mail,proto3" json:"mail,omitempty"`                         // 邮箱（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UpdateRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

// 检查用户名请求
type CheckUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameRequest) Reset() {
	*x = CheckUsernameRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameRequest) ProtoMessage() {}

func (x *CheckUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *CheckUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// 检查用户是否登录请求
type CheckLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckLoginRequest) Reset() {
	*x = CheckLoginRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckLoginRequest) ProtoMessage() {}

func (x *CheckLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckLoginRequest.ProtoReflect.Descriptor instead.
func (*CheckLoginRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *CheckLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CheckLoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 检查用户名响应
type CheckUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exist         bool                   `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"` // 是否存在
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameResponse) Reset() {
	*x = CheckUsernameResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameResponse) ProtoMessage() {}

func (x *CheckUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *CheckUsernameResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

// 通用响应
type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 错误信息(如果有)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 用户退出登录请求
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`       // Token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 创建分组请求
type GroupSaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`   // 发起创建的用户名
	GroupName     string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"` // 分组名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSaveRequest) Reset() {
	*x = GroupSaveRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSaveRequest) ProtoMessage() {}

func (x *GroupSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSaveRequest.ProtoReflect.Descriptor instead.
func (*GroupSaveRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *GroupSaveRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupSaveRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

// 更新分组请求
type GroupUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`           // 分组标识
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`         // 分组名称
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"` // 添加用户名字段，用于权限验证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUpdateRequest) Reset() {
	*x = GroupUpdateRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdateRequest) ProtoMessage() {}

func (x *GroupUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdateRequest.ProtoReflect.Descriptor instead.
func (*GroupUpdateRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *GroupUpdateRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *GroupUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupUpdateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// 分组排序请求
type GroupSortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`                               // 分组标识
	SortOrder     int32                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // 排序序号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSortRequest) Reset() {
	*x = GroupSortRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSortRequest) ProtoMessage() {}

func (x *GroupSortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSortRequest.ProtoReflect.Descriptor instead.
func (*GroupSortRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *GroupSortRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *GroupSortRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// 分组信息响应
type GroupResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gid            string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`                                                // 分组标识
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // 分组名称
	SortOrder      int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`                  // 排序序号
	ShortLinkCount int32                  `protobuf:"varint,4,opt,name=short_link_count,json=shortLinkCount,proto3" json:"short_link_count,omitempty"` // 短链接数量
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{14}
}

func (x *GroupResponse) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *GroupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupResponse) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *GroupResponse) GetShortLinkCount() int32 {
	if x != nil {
		return x.ShortLinkCount
	}
	return 0
}

// 删除分组请求
type GroupDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"` // 分组标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDeleteRequest) Reset() {
	*x = GroupDeleteRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDeleteRequest) ProtoMessage() {}

func (x *GroupDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDeleteRequest.ProtoReflect.Descriptor instead.
func (*GroupDeleteRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{15}
}

func (x *GroupDeleteRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

// 回收站分页查询请求
type RecycleBinPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GidList       []string               `protobuf:"bytes,1,rep,name=gid_list,json=gidList,proto3" json:"gid_list,omitempty"`     // 分组标识列表，可选
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`    // 当前页码，从1开始
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecycleBinPageRequest) Reset() {
	*x = RecycleBinPageRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecycleBinPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleBinPageRequest) ProtoMessage() {}

func (x *RecycleBinPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleBinPageRequest.ProtoReflect.Descriptor instead.
func (*RecycleBinPageRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{16}
}

func (x *RecycleBinPageRequest) GetGidList() []string {
	if x != nil {
		return x.GidList
	}
	return nil
}

func (x *RecycleBinPageRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *RecycleBinPageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 回收站分页查询响应
type RecycleBinPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ShortLinkPageRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`  // 短链接记录列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`     // 总记录数
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`       // 每页大小
	Current       int32                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"` // 当前页码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecycleBinPageResponse) Reset() {
	*x = RecycleBinPageResponse{}
	mi := &file_user_rpc_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecycleBinPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecycleBinPageResponse) ProtoMessage() {}

func (x *RecycleBinPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecycleBinPageResponse.ProtoReflect.Descriptor instead.
func (*RecycleBinPageResponse) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{17}
}

func (x *RecycleBinPageResponse) GetRecords() []*ShortLinkPageRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *RecycleBinPageResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RecycleBinPageResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RecycleBinPageResponse) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

// 短链接分页记录
type ShortLinkPageRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 短链接ID
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                                       // 域名
	ShortUri      string                 `protobuf:"bytes,3,opt,name=short_uri,json=shortUri,proto3" json:"short_uri,omitempty"`                   // 短链接URI
	FullShortUrl  string                 `protobuf:"bytes,4,opt,name=full_short_url,json=fullShortUrl,proto3" json:"full_short_url,omitempty"`     // 完整短链接
	OriginUrl     string                 `protobuf:"bytes,5,opt,name=origin_url,json=originUrl,proto3" json:"origin_url,omitempty"`                // 原始链接
	Gid           string                 `protobuf:"bytes,6,opt,name=gid,proto3" json:"gid,omitempty"`                                             // 分组标识
	ValidDateType int32                  `protobuf:"varint,7,opt,name=valid_date_type,json=validDateType,proto3" json:"valid_date_type,omitempty"` // 有效期类型：0永久有效，1自定义
	ValidDate     string                 `protobuf:"bytes,8,opt,name=valid_date,json=validDate,proto3" json:"valid_date,omitempty"`                // 有效期
	CreateTime    string                 `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`             // 创建时间
	Describe      string                 `protobuf:"bytes,10,opt,name=describe,proto3" json:"describe,omitempty"`                                  // 描述
	Favicon       string                 `protobuf:"bytes,11,opt,name=favicon,proto3" json:"favicon,omitempty"`                                    // 网站图标
	EnableStatus  int32                  `protobuf:"varint,12,opt,name=enable_status,json=enableStatus,proto3" json:"enable_status,omitempty"`     // 启用状态：0启用，1未启用
	TotalPv       int64                  `protobuf:"varint,13,opt,name=total_pv,json=totalPv,proto3" json:"total_pv,omitempty"`                    // 总访问量
	TodayPv       int64                  `protobuf:"varint,14,opt,name=today_pv,json=todayPv,proto3" json:"today_pv,omitempty"`                    // 今日访问量
	TotalUv       int64                  `protobuf:"varint,15,opt,name=total_uv,json=totalUv,proto3" json:"total_uv,omitempty"`                    // 总独立访客数
	TodayUv       int64                  `protobuf:"varint,16,opt,name=today_uv,json=todayUv,proto3" json:"today_uv,omitempty"`                    // 今日独立访客数
	TotalUip      int64                  `protobuf:"varint,17,opt,name=total_uip,json=totalUip,proto3" json:"total_uip,omitempty"`                 // 总IP数
	TodayUip      int64                  `protobuf:"varint,18,opt,name=today_uip,json=todayUip,proto3" json:"today_uip,omitempty"`                 // 今日IP数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortLinkPageRecord) Reset() {
	*x = ShortLinkPageRecord{}
	mi := &file_user_rpc_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortLinkPageRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortLinkPageRecord) ProtoMessage() {}

func (x *ShortLinkPageRecord) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortLinkPageRecord.ProtoReflect.Descriptor instead.
func (*ShortLinkPageRecord) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{18}
}

func (x *ShortLinkPageRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShortLinkPageRecord) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ShortLinkPageRecord) GetShortUri() string {
	if x != nil {
		return x.ShortUri
	}
	return ""
}

func (x *ShortLinkPageRecord) GetFullShortUrl() string {
	if x != nil {
		return x.FullShortUrl
	}
	return ""
}

func (x *ShortLinkPageRecord) GetOriginUrl() string {
	if x != nil {
		return x.OriginUrl
	}
	return ""
}

func (x *ShortLinkPageRecord) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *ShortLinkPageRecord) GetValidDateType() int32 {
	if x != nil {
		return x.ValidDateType
	}
	return 0
}

func (x *ShortLinkPageRecord) GetValidDate() string {
	if x != nil {
		return x.ValidDate
	}
	return ""
}

func (x *ShortLinkPageRecord) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *ShortLinkPageRecord) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *ShortLinkPageRecord) GetFavicon() string {
	if x != nil {
		return x.Favicon
	}
	return ""
}

func (x *ShortLinkPageRecord) GetEnableStatus() int32 {
	if x != nil {
		return x.EnableStatus
	}
	return 0
}

func (x *ShortLinkPageRecord) GetTotalPv() int64 {
	if x != nil {
		return x.TotalPv
	}
	return 0
}

func (x *ShortLinkPageRecord) GetTodayPv() int64 {
	if x != nil {
		return x.TodayPv
	}
	return 0
}

func (x *ShortLinkPageRecord) GetTotalUv() int64 {
	if x != nil {
		return x.TotalUv
	}
	return 0
}

func (x *ShortLinkPageRecord) GetTodayUv() int64 {
	if x != nil {
		return x.TodayUv
	}
	return 0
}

func (x *ShortLinkPageRecord) GetTotalUip() int64 {
	if x != nil {
		return x.TotalUip
	}
	return 0
}

func (x *ShortLinkPageRecord) GetTodayUip() int64 {
	if x != nil {
		return x.TodayUip
	}
	return 0
}

// 通用请求（空参数）
type CommonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRequest) Reset() {
	*x = CommonRequest{}
	mi := &file_user_rpc_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRequest) ProtoMessage() {}

func (x *CommonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRequest.ProtoReflect.Descriptor instead.
func (*CommonRequest) Descriptor() ([]byte, []int) {
	return file_user_rpc_user_proto_rawDescGZIP(), []int{19}
}

var File_user_rpc_user_proto protoreflect.FileDescriptor

const file_user_rpc_user_proto_rawDesc = "" +
	"\n" +
	"\x13user/rpc/user.proto\x12\x04user\"\x90\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04mail\x18\x05 \x01(\tR\x04mail\"i\n" +
	"\x10RegisterResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\tR\n" +
	"createTime\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x7f\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\tR\n" +
	"createTime\"\xc7\x01\n" +
	"\x10UserInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04mail\x18\x05 \x01(\tR\x04mail\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\tR\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\tR\n" +
	"updateTime\"\x8e\x01\n" +
	"\rUpdateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\treal_name\x18\x03 \x01(\tR\brealName\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04mail\x18\x05 \x01(\tR\x04mail\"2\n" +
	"\x14CheckUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"E\n" +
	"\x11CheckLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"-\n" +
	"\x15CheckUsernameResponse\x12\x14\n" +
	"\x05exist\x18\x01 \x01(\bR\x05exist\"D\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\rLogoutRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"L\n" +
	"\x10GroupSaveRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\"V\n" +
	"\x12GroupUpdateRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"C\n" +
	"\x10GroupSortRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x05R\tsortOrder\"~\n" +
	"\rGroupResponse\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\x12(\n" +
	"\x10short_link_count\x18\x04 \x01(\x05R\x0eshortLinkCount\"&\n" +
	"\x12GroupDeleteRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\"j\n" +
	"\x15RecycleBinPageRequest\x12\x19\n" +
	"\bgid_list\x18\x01 \x03(\tR\agidList\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x91\x01\n" +
	"\x16RecycleBinPageResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.user.ShortLinkPageRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x05R\acurrent\"\x9a\x04\n" +
	"\x13ShortLinkPageRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1b\n" +
	"\tshort_uri\x18\x03 \x01(\tR\bshortUri\x12$\n" +
	"\x0efull_short_url\x18\x04 \x01(\tR\ffullShortUrl\x12\x1d\n" +
	"\n" +
	"origin_url\x18\x05 \x01(\tR\toriginUrl\x12\x10\n" +
	"\x03gid\x18\x06 \x01(\tR\x03gid\x12&\n" +
	"\x0fvalid_date_type\x18\a \x01(\x05R\rvalidDateType\x12\x1d\n" +
	"\n" +
	"valid_date\x18\b \x01(\tR\tvalidDate\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\tR\n" +
	"createTime\x12\x1a\n" +
	"\bdescribe\x18\n" +
	" \x01(\tR\bdescribe\x12\x18\n" +
	"\afavicon\x18\v \x01(\tR\afavicon\x12#\n" +
	"\renable_status\x18\f \x01(\x05R\fenableStatus\x12\x19\n" +
	"\btotal_pv\x18\r \x01(\x03R\atotalPv\x12\x19\n" +
	"\btoday_pv\x18\x0e \x01(\x03R\atodayPv\x12\x19\n" +
	"\btotal_uv\x18\x0f \x01(\x03R\atotalUv\x12\x19\n" +
	"\btoday_uv\x18\x10 \x01(\x03R\atodayUv\x12\x1b\n" +
	"\ttotal_uip\x18\x11 \x01(\x03R\btotalUip\x12\x1b\n" +
	"\ttoday_uip\x18\x12 \x01(\x03R\btodayUip\"\x0f\n" +
	"\rCommonRequest2\x8d\a\n" +
	"\vUserService\x12=\n" +
	"\fUserRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x124\n" +
	"\tUserLogin\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12A\n" +
	"\vUserGetInfo\x12\x1a.user.CheckUsernameRequest\x1a\x16.user.UserInfoResponse\x12G\n" +
	"\x11UserGetActualInfo\x12\x1a.user.CheckUsernameRequest\x1a\x16.user.UserInfoResponse\x12L\n" +
	"\x11UserCheckUsername\x12\x1a.user.CheckUsernameRequest\x1a\x1b.user.CheckUsernameResponse\x127\n" +
	"\n" +
	"UserUpdate\x12\x13.user.UpdateRequest\x1a\x14.user.CommonResponse\x12?\n" +
	"\x0eUserCheckLogin\x12\x17.user.CheckLoginRequest\x1a\x14.user.CommonResponse\x127\n" +
	"\n" +
	"UserLogout\x12\x13.user.LogoutRequest\x1a\x14.user.CommonResponse\x12;\n" +
	"\vGroupCreate\x12\x16.user.GroupSaveRequest\x1a\x14.user.CommonResponse\x127\n" +
	"\tGroupList\x12\x13.user.CommonRequest\x1a\x13.user.GroupResponse0\x01\x12=\n" +
	"\vGroupUpdate\x12\x18.user.GroupUpdateRequest\x1a\x14.user.CommonResponse\x12=\n" +
	"\vGroupDelete\x12\x18.user.GroupDeleteRequest\x1a\x14.user.CommonResponse\x12;\n" +
	"\tGroupSort\x12\x16.user.GroupSortRequest\x1a\x14.user.CommonResponse(\x01\x12K\n" +
	"\x0eRecycleBinPage\x12\x1b.user.RecycleBinPageRequest\x1a\x1c.user.RecycleBinPageResponseB\x04Z\x02./b\x06proto3"

var (
	file_user_rpc_user_proto_rawDescOnce sync.Once
	file_user_rpc_user_proto_rawDescData []byte
)

func file_user_rpc_user_proto_rawDescGZIP() []byte {
	file_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_rpc_user_proto_rawDesc), len(file_user_rpc_user_proto_rawDesc)))
	})
	return file_user_rpc_user_proto_rawDescData
}

var file_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_user_rpc_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: user.RegisterRequest
	(*RegisterResponse)(nil),       // 1: user.RegisterResponse
	(*LoginRequest)(nil),           // 2: user.LoginRequest
	(*LoginResponse)(nil),          // 3: user.LoginResponse
	(*UserInfoResponse)(nil),       // 4: user.UserInfoResponse
	(*UpdateRequest)(nil),          // 5: user.UpdateRequest
	(*CheckUsernameRequest)(nil),   // 6: user.CheckUsernameRequest
	(*CheckLoginRequest)(nil),      // 7: user.CheckLoginRequest
	(*CheckUsernameResponse)(nil),  // 8: user.CheckUsernameResponse
	(*CommonResponse)(nil),         // 9: user.CommonResponse
	(*LogoutRequest)(nil),          // 10: user.LogoutRequest
	(*GroupSaveRequest)(nil),       // 11: user.GroupSaveRequest
	(*GroupUpdateRequest)(nil),     // 12: user.GroupUpdateRequest
	(*GroupSortRequest)(nil),       // 13: user.GroupSortRequest
	(*GroupResponse)(nil),          // 14: user.GroupResponse
	(*GroupDeleteRequest)(nil),     // 15: user.GroupDeleteRequest
	(*RecycleBinPageRequest)(nil),  // 16: user.RecycleBinPageRequest
	(*RecycleBinPageResponse)(nil), // 17: user.RecycleBinPageResponse
	(*ShortLinkPageRecord)(nil),    // 18: user.ShortLinkPageRecord
	(*CommonRequest)(nil),          // 19: user.CommonRequest
}
var file_user_rpc_user_proto_depIdxs = []int32{
	18, // 0: user.RecycleBinPageResponse.records:type_name -> user.ShortLinkPageRecord
	0,  // 1: user.UserService.UserRegister:input_type -> user.RegisterRequest
	2,  // 2: user.UserService.UserLogin:input_type -> user.LoginRequest
	6,  // 3: user.UserService.UserGetInfo:input_type -> user.CheckUsernameRequest
	6,  // 4: user.UserService.UserGetActualInfo:input_type -> user.CheckUsernameRequest
	6,  // 5: user.UserService.UserCheckUsername:input_type -> user.CheckUsernameRequest
	5,  // 6: user.UserService.UserUpdate:input_type -> user.UpdateRequest
	7,  // 7: user.UserService.UserCheckLogin:input_type -> user.CheckLoginRequest
	10, // 8: user.UserService.UserLogout:input_type -> user.LogoutRequest
	11, // 9: user.UserService.GroupCreate:input_type -> user.GroupSaveRequest
	19, // 10: user.UserService.GroupList:input_type -> user.CommonRequest
	12, // 11: user.UserService.GroupUpdate:input_type -> user.GroupUpdateRequest
	15, // 12: user.UserService.GroupDelete:input_type -> user.GroupDeleteRequest
	13, // 13: user.UserService.GroupSort:input_type -> user.GroupSortRequest
	16, // 14: user.UserService.RecycleBinPage:input_type -> user.RecycleBinPageRequest
	1,  // 15: user.UserService.UserRegister:output_type -> user.RegisterResponse
	3,  // 16: user.UserService.UserLogin:output_type -> user.LoginResponse
	4,  // 17: user.UserService.UserGetInfo:output_type -> user.UserInfoResponse
	4,  // 18: user.UserService.UserGetActualInfo:output_type -> user.UserInfoResponse
	8,  // 19: user.UserService.UserCheckUsername:output_type -> user.CheckUsernameResponse
	9,  // 20: user.UserService.UserUpdate:output_type -> user.CommonResponse
	9,  // 21: user.UserService.UserCheckLogin:output_type -> user.CommonResponse
	9,  // 22: user.UserService.UserLogout:output_type -> user.CommonResponse
	9,  // 23: user.UserService.GroupCreate:output_type -> user.CommonResponse
	14, // 24: user.UserService.GroupList:output_type -> user.GroupResponse
	9,  // 25: user.UserService.GroupUpdate:output_type -> user.CommonResponse
	9,  // 26: user.UserService.GroupDelete:output_type -> user.CommonResponse
	9,  // 27: user.UserService.GroupSort:output_type -> user.CommonResponse
	17, // 28: user.UserService.RecycleBinPage:output_type -> user.RecycleBinPageResponse
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_rpc_user_proto_init() }
func file_user_rpc_user_proto_init() {
	if File_user_rpc_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_rpc_user_proto_rawDesc), len(file_user_rpc_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_user_rpc_user_proto_msgTypes,
	}.Build()
	File_user_rpc_user_proto = out.File
	file_user_rpc_user_proto_goTypes = nil
	file_user_rpc_user_proto_depIdxs = nil
}
