// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"go-zero-shorterurl/admin/internal/dal/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.TUser{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.TUser{}) fail: %s", err)
	}
}

func Test_tUserQuery(t *testing.T) {
	tUser := newTUser(_gen_test_db)
	tUser = *tUser.As(tUser.TableName())
	_do := tUser.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(tUser.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <t_user> fail:", err)
		return
	}

	_, ok := tUser.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from tUser success")
	}

	err = _do.Create(&model.TUser{})
	if err != nil {
		t.Error("create item in table <t_user> fail:", err)
	}

	err = _do.Save(&model.TUser{})
	if err != nil {
		t.Error("create item in table <t_user> fail:", err)
	}

	err = _do.CreateInBatches([]*model.TUser{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <t_user> fail:", err)
	}

	_, err = _do.Select(tUser.ALL).Take()
	if err != nil {
		t.Error("Take() on table <t_user> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <t_user> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <t_user> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <t_user> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.TUser{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <t_user> fail:", err)
	}

	_, err = _do.Select(tUser.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <t_user> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <t_user> fail:", err)
	}

	_, err = _do.Select(tUser.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <t_user> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <t_user> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <t_user> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <t_user> fail:", err)
	}

	_, err = _do.ScanByPage(&model.TUser{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <t_user> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <t_user> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <t_user> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <t_user> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <t_user> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <t_user> fail:", err)
	}
}
