// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTGroupUnique = "t_group_unique"

// TGroupUnique mapped from table <t_group_unique>
type TGroupUnique struct {
	ID  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Gid string `gorm:"column:gid;comment:分组标识" json:"gid"`                           // 分组标识
}

// TableName TGroupUnique's table name
func (*TGroupUnique) TableName() string {
	return TableNameTGroupUnique
}
