// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTGroup = "t_group"

// TGroup mapped from table <t_group>
type TGroup struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Gid        string    `gorm:"column:gid;comment:分组标识" json:"gid"`                           // 分组标识
	Name       string    `gorm:"column:name;comment:分组名称" json:"name"`                         // 分组名称
	Username   string    `gorm:"column:username;comment:创建分组用户名" json:"username"`              // 创建分组用户名
	SortOrder  int32     `gorm:"column:sort_order;comment:分组排序" json:"sort_order"`             // 分组排序
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`           // 修改时间
	DelFlag    bool      `gorm:"column:del_flag;comment:删除标识 0：未删除 1：已删除" json:"del_flag"`     // 删除标识 0：未删除 1：已删除
}

// TableName TGroup's table name
func (*TGroup) TableName() string {
	return TableNameTGroup
}
