// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTLink = "t_link"

// TLink mapped from table <t_link>
type TLink struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`             // ID
	Domain        string    `gorm:"column:domain;comment:域名" json:"domain"`                                   // 域名
	ShortURI      string    `gorm:"column:short_uri;comment:短链接" json:"short_uri"`                            // 短链接
	FullShortURL  string    `gorm:"column:full_short_url;comment:完整短链接" json:"full_short_url"`                // 完整短链接
	OriginURL     string    `gorm:"column:origin_url;comment:原始链接" json:"origin_url"`                         // 原始链接
	ClickNum      int32     `gorm:"column:click_num;comment:点击量" json:"click_num"`                            // 点击量
	Gid           string    `gorm:"column:gid;default:default;comment:分组标识" json:"gid"`                       // 分组标识
	Favicon       string    `gorm:"column:favicon;comment:网站图标" json:"favicon"`                               // 网站图标
	EnableStatus  bool      `gorm:"column:enable_status;comment:启用标识 0：启用 1：未启用" json:"enable_status"`        // 启用标识 0：启用 1：未启用
	CreatedType   bool      `gorm:"column:created_type;comment:创建类型 0：接口创建 1：控制台创建" json:"created_type"`      // 创建类型 0：接口创建 1：控制台创建
	ValidDateType bool      `gorm:"column:valid_date_type;comment:有效期类型 0：永久有效 1：自定义" json:"valid_date_type"` // 有效期类型 0：永久有效 1：自定义
	ValidDate     time.Time `gorm:"column:valid_date;comment:有效期" json:"valid_date"`                          // 有效期
	Describe      string    `gorm:"column:describe;comment:描述" json:"describe"`                               // 描述
	TotalPv       int32     `gorm:"column:total_pv;comment:历史PV" json:"total_pv"`                             // 历史PV
	TotalUv       int32     `gorm:"column:total_uv;comment:历史UV" json:"total_uv"`                             // 历史UV
	TotalUip      int32     `gorm:"column:total_uip;comment:历史UIP" json:"total_uip"`                          // 历史UIP
	CreateTime    time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`                       // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`                       // 修改时间
	DelTime       int64     `gorm:"column:del_time;comment:删除时间戳" json:"del_time"`                            // 删除时间戳
	DelFlag       bool      `gorm:"column:del_flag;comment:删除标识 0：未删除 1：已删除" json:"del_flag"`                 // 删除标识 0：未删除 1：已删除
}

// TableName TLink's table name
func (*TLink) TableName() string {
	return TableNameTLink
}
