// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTUser = "t_user"

// TUser mapped from table <t_user>
type TUser struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Username     string    `gorm:"column:username;comment:用户名" json:"username"`                  // 用户名
	Password     string    `gorm:"column:password;comment:密码" json:"password"`                   // 密码
	RealName     string    `gorm:"column:real_name;comment:真实姓名" json:"real_name"`               // 真实姓名
	Phone        string    `gorm:"column:phone;comment:手机号" json:"phone"`                        // 手机号
	Mail         string    `gorm:"column:mail;comment:邮箱" json:"mail"`                           // 邮箱
	DeletionTime int64     `gorm:"column:deletion_time;comment:注销时间戳" json:"deletion_time"`      // 注销时间戳
	CreateTime   time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`           // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`           // 修改时间
	DelFlag      bool      `gorm:"column:del_flag;comment:删除标识 0：未删除 1：已删除" json:"del_flag"`     // 删除标识 0：未删除 1：已删除
}

// TableName TUser's table name
func (*TUser) TableName() string {
	return TableNameTUser
}
